version: '3'

services:
  update-service:
    image: 2271432/update_service:latest
    platform: linux/amd64
    command: python3 deploy/deploy_contract.py
    environment:
      - WEB3_PROVIDER=http://host.docker.internal:8545
      - ACCOUNT_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    volumes:
      - ./:/app
      - ../registry-service:/app/registry-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    restart: "no"

networks:
  update_network:
    driver: bridge
